sf: 4
degradation:
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.3, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 15]
  poisson_scale_range: [0.05, 2.0]
  gray_noise_prob: 0.4
  jpeg_range: [60, 95]

  # the second degradation process
  second_blur_prob: 0.5
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.6, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 12]
  poisson_scale_range2: [0.05, 1.0]
  gray_noise_prob2: 0.4
  jpeg_range2: [60, 100]

  gt_size: 512
  no_degradation_prob: 0.01

train:
  queue_size: 180
  gt_path: ['dataset_path/LSDIR/']
  face_gt_path: 'dataset_path/FFHQ/'
  num_face: 10000
  crop_size: 512
  io_backend:
    type: disk

  blur_kernel_size: 21
  kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob: 0.1
  blur_sigma: [0.2, 1.5]
  betag_range: [0.5, 2.0]
  betap_range: [1, 1.5]

  blur_kernel_size2: 11
  kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob2: 0.1
  blur_sigma2: [0.2, 1.0]
  betag_range2: [0.5, 2.0]
  betap_range2: [1, 1.5]

  final_sinc_prob: 0.8

  gt_size: 512
  use_hflip: True
  use_rot: False

validation:
  gt_path: dataset_path/DIV2K_valid_HR/
  crop_size: 512
  io_backend:
    type: disk

  blur_kernel_size: 21
  kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob: 0.1
  blur_sigma: [0.2, 1.5]
  betag_range: [0.5, 2.0]
  betap_range: [1, 1.5]

  blur_kernel_size2: 11
  kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob2: 0.1
  blur_sigma2: [0.2, 1.0]
  betag_range2: [0.5, 2.0]
  betap_range2: [1, 1.5]

  final_sinc_prob: 0.8

  gt_size: 512
  use_hflip: True
  use_rot: False

test:
  gt_path: dataset_path/DIV2K_valid_HR/
  crop_size: 512
  io_backend:
    type: disk

  blur_kernel_size: 21
  kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob: 0.1
  blur_sigma: [0.2, 1.5]
  betag_range: [0.5, 2.0]
  betap_range: [1, 1.5]

  blur_kernel_size2: 11
  kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
  sinc_prob2: 0.1
  blur_sigma2: [0.2, 1.0]
  betag_range2: [0.5, 2.0]
  betap_range2: [1, 1.5]

  final_sinc_prob: 0.8

  gt_size: 512
  use_hflip: True
  use_rot: False